version: "3"

services:
  
  database:
    image: postgres:9
    restart: unless-stopped
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: mydb
      POSTGRES_USER: kajtu
    volumes:
      - ./database:/var/lib/postgresql/data

