openapi: '3.0.0'
components:
  schemas:
    CreateStudent:
      type: object
      properties:
        id_kierunek:
          type: integer
          example: 6
        imie:
          type: string
          example: "Kajetan"
        nazwisko:
          type: string
          example: "Kacprzyk"
        pesel:
          type: string
          example: "21372137420"
        telefon:
          type: string
          example: "123456789"
        rok_studiow:
          type: integer
          example: 5

    Student:
      type: object
      properties:
        id_student:
          type: integer
          example: 3
        id_kierunek:
          type: integer
          example: 6
        imie:
          type: string
          example: "Kajetan"
        nazwisko:
          type: string
          example: "Kacprzyk"
        pesel:
          type: string
          example: "21372137420"
        telefon:
          type: string
          example: "123456789"
        rok_studiow:
          type: integer
          example: 5

    StudentsResponse:
      type: array
      items:
        $ref: '#/components/schemas/Student'


info:
  title: API Title
  version: '1.0'
servers:
  - url: http://localhost:3000
paths:
  /studenci:
    get:
      responses:
        '200':
          description: "List of students"
          content:
            'application/json':
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Student'

                

